# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: sash

builds:
  - skip: true

dockers_v2:
  - images:
      - ghcr.io/davidkovach-fuentes/sash
    tags:
      - "{{ .Tag }}"
    platforms:
      - linux/amd64
      - linux/arm64

    dockerfile: Dockerfile

    extra_files:
      - pyproject.toml
      - uv.lock
      - README.md
      - src

    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
