# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: asash

builds:
  - id: wheel
    builder: uv
    buildmode: wheel

  - id: sdist
    builder: uv
    buildmode: sdist
    env:
      - CFLAGS=-std=gnu17

checksum:
  name_template: checksums.txt

nfpms:
  - id: packages
    package_name: sash
    vendor: Brown University
    homepage: https://github.com/atlas-brown/sash
    maintainer: John Brown <john_brown@brown.edu>
    description: A static analysis tool for the shell based on symbolic execution
    license: MIT

    formats:
      - deb
      - rpm

    meta: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

sboms:
  - artifacts: archive


